server:
  port: 8000
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8

spring:
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  profiles:
    active: @profileActive@
  main:
    allow-bean-definition-overriding: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 1800 #JWT的超期限时间(30*60)
  tokenHead: Bearer  #JWT负载中拿到开头

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
